services:
  - type: web
    name: medallia-rag-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false
      - key: VECTOR_STORE_ID
        sync: false